### ISSUE TITLE
Dependent entities type script conversion issue

### ISSUE THREAD

**Issue by srijithkrishnan1** [ptc-iot-sharing/ThingworxVSCodeProject#13]
Getting the following errors while building. Error is seen for all the entities that are downloaded part of the dependent project mentioned in the project dependencies. 

> tw_imports\Things\DeviceSerialMapping.DT.d.ts(1,53): error TS2314: Generic type 'DataTable<T>' requires 1 type argument(s).

> tw_imports\Things\IngestionCoordinatorClient.Thing.d.ts(36,260): error TS1055: Type 'NOTHING' is not a valid async function return type in ES5/ES3 because it does not refer to a Promise-compatible constructor value.

> tw_imports\ThingTemplates\AxisMovementStream.Template.d.ts(11,63): error TS2344: Type 'AxisMovementStream_Template' does not satisfy the constraint 'GenericThing'.
  Type 'AxisMovementStream_Template' is missing the following properties from type 'GenericThing': name, description, thingTemplate, tags, and 234 more.

**Comment by BogdanMihaiciuc** [comment]
I will take a look. Most likely these are just some situations that I handle properly when pulling declarations from the server.

It looks like the issue occurs with:
- data tables
- async services
- streams

Does this happen with all other entities like this, or is this something specific to those three?

**Comment by BogdanMihaiciuc** [comment]
Grab the latest `gulpfile.js` which contains the fixes and try the import again; let me know if you are still running into issues.

Note that if you are using remote streams or remote data tables you should also grab the updated `static/base/ThingTemplates.d.ts` which adds a generic type parameter to those templates.

**Comment by BogdanMihaiciuc** [comment]
If your issue still isn't resolved by the recent changes please reopen the issue.

**Comment by carlo-quinonez** [comment]
@srijithkrishnan1 Can you check if this resolved our problem?

@BogdanMihaiciuc Thank you for looking at this issue.
