### ISSUE TITLE
Undesired quotes in tw_imports ThingTemplates

### ISSUE THREAD

**Issue by TG-JC** [ptc-iot-sharing/ThingworxVSCodeProject#3]
I get this error from gulp build:

> [13:48:55] Starting 'build'...
> tw_imports/ThingTemplates/EnergyStorage_MicroGridTT.d.ts(1,73): error TS2345: Argument of type '"MirisGenericThing"' is not assignable to parameter of type 'Constructor<GenericThing>'.
> tw_imports/ThingTemplates/MiRIS_BatteryTT.d.ts(1,63): error TS2345: Argument of type '"MirisGenericThing"' is not assignable to parameter of type 'Constructor<GenericThing>'.
> tw_imports/ThingTemplates/MiRIS_ConsumerTT.d.ts(1,64): error TS2345: Argument of type '"MirisGenericThing"' is not assignable to parameter of type 'Constructor<GenericThing>'.
> tw_imports/ThingTemplates/MiRIS_GensetTT.d.ts(1,62): error TS2345: Argument of type '"MirisGenericThing"' is not assignable to parameter of type 'Constructor<GenericThing>'.
> tw_imports/ThingTemplates/MiRIS_InverterGroupTT.d.ts(1,69): error TS2345: Argument of type '"MirisGenericThing"' is not assignable to parameter of type 'Constructor<GenericThing>'.
> tw_imports/ThingTemplates/MiRIS_LoadBankTT.d.ts(1,64): error TS2345: Argument of type '"MirisGenericThing"' is not assignable to parameter of type 'Constructor<GenericThing>'.
> tw_imports/Things/MiRIS_Data_Gateway.d.ts(1,66): error TS2345: Argument of type '"RemoteThing"' is not assignable to parameter of type 'Constructor<GenericThing>'.
> tw_imports/Things/MiRIS_GridThing.d.ts(1,63): error TS2345: Argument of type '"MirisGenericThing"' is not assignable to parameter of type 'Constructor<GenericThing>'.
> tw_imports/Things/MiRIS_MicroGrid.d.ts(1,63): error TS2345: Argument of type '"EnergyStorage_MicroGridTT"' is not assignable to parameter of type 'Constructor<GenericThing>'.
> TypeScript: 9 semantic errors
> (...)

Looking at the file refered to by first line, I see:
> declare class EnergyStorage_MicroGridTT extends ThingTemplateWithShapes("MirisGenericThing", "JCockpit_SiteTS") {

FYI MirisGenericThing is just a TT derived from GenericThing with a ValueStream added to it

If I remove the quotes around first argument, I then get an error on second one.
> [13:51:02] Starting 'build'...
> tw_imports/ThingTemplates/EnergyStorage_MicroGridTT.d.ts(1,92): error TS2345: Argument of type '"JCockpit_SiteTS"' is not assignable to parameter of type 'Constructor<ThingShapeBase>'.
> (...)

If I remove the quotes around second argument, build is OK for this file. I have to fix to every one.
> [13:51:56] Starting 'build'...
> tw_imports/ThingTemplates/MiRIS_BatteryTT.d.ts(1,63): error TS2345: Argument of type '"MirisGenericThing"' is not assignable to parameter of type 'Constructor<GenericThing>'.

It seems the extractor adds quotes at a wrong place.

**Comment by BogdanMihaiciuc** [comment]
This should be fixed with e94837167858fe95ef98679b9dcec91948f8cf62.

After updating your gulpfile, rerun gulp install and let me know if you still get build errors.

Make sure to also use the latest version of `bm-thing-transformer` from npm.

**Comment by TG-JC** [comment]
I confirm this commit fixes the issue, using 0.9.0 for bm-thing-transformer. Thank you.

FYI, I had to add a file with
> declare class NetworkEntity extends RootEntity {
> }
to get rid of a missing declaration.
I know Network is currently not supported, but it is retrieved by gulp install as it belongs to my project.

**Comment by BogdanMihaiciuc** [comment]
Network entity type declarations missing are an oversight and I'll look into adding them by the next update.

Thanks!
