### ISSUE TITLE
NUMBER instead of number

### ISSUE THREAD

**Issue by TG-JC** [ptc-iot-sharing/ThingworxVSCodeProject#4]
In default MyThing.ts file, this line is faulty:
> @persistent numberProperty!: number;

It has to be "NUMBER" instead of "number" for build to pass.

I saw a commit telling it should pass with lowercase, but it doesn't.

**Comment by BogdanMihaiciuc** [comment]
Thanks for the report; I will update the project to resolve this soon.

In the meantime, the fix should be to update to the latest version of the `"bm-thing-transformer"` dependency (`"^0.9.0"`) and run `npm install` to grab it from npm.

**Comment by BogdanMihaiciuc** [comment]
Fixed in the template via bddd8acae01662305a6ab727624e353ae4b207c6.

**Comment by TG-JC** [comment]
I confirm the fix
