### ISSUE TITLE
Expose SubSystems services (similar to Resources)

### ISSUE THREAD

**Issue by dattosma** [ptc-iot-sharing/ThingworxVSCodeProject#5]
SubSystems and their respective services are not exposed in TS code.
For example : Subsystems.PlatformSubsystem.GetExtensionPackageList()

**Comment by BogdanMihaiciuc** [comment]
The subsystem definitions are now included in the project and you grab the file from `/static/base/Subsystems.d.ts`: https://github.com/ptc-iot-sharing/ThingworxVSCodeProject/blob/master/static/base/Subsystems.d.ts

**Comment by dattosma** [comment]
Thanks a lot Borgdan.
