### ISSUE TITLE
Ability to specify ordinal information on DataShape fields

### ISSUE THREAD

**Issue by dattosma** [ptc-iot-sharing/ThingworxVSCodeProject#6]
It would be nice to be able to specify **ordinal** information on DataShape fields.

**Comment by BogdanMihaiciuc** [comment]
Support addded via https://github.com/ptc-iot-sharing/ThingworxVSCodeProject/commit/a83ff8727103a4106e25b403913fb764b6bac023, https://github.com/BogdanMihaiciuc/ThingTransformer/commit/3fb5922ab9f2640fd3a5450693ff065e092c03d5 and https://github.com/BogdanMihaiciuc/ThingTransformer/commit/024d85c5a6b1847a181b7d87cd83107aea472970.

To use, make sure to update to the latest thing transformer version (0.10) and include the definition for the `@ordinal` decorator from the `static/base/Decorators.d.ts` file:
https://github.com/ptc-iot-sharing/ThingworxVSCodeProject/blob/4be010d7b676a12416a346ad938f225607acf89b/static/base/Decorators.d.ts#L84-L87

If this solves your problem, please close this issue.

**Comment by dattosma** [comment]
@ordinal decorator is working on my side. Thanks a lot Bogdan.

**Comment by dattosma** [comment]
@ordinal decorator is working on my side. Thanks a lot Bogdan.
