### ISSUE TITLE
Transitive dependencies of top level functions are not always copied in services

### ISSUE THREAD

**Issue by kklorenzotesta** [ptc-iot-sharing/ThingworxVSCodeProject#66]
If I have a top level function that call another one like:
```
function f2() {
  logger.error("F2");
}

function f1() {
  f2();
}

@ThingDefinition
class ThingB extends GenericThing {}
```
and f1 is called by a service in a Thing in a file that precedes alphabetically the file containing the function definitions, then f2 is not copied inside the service.
Instead the service
```
@ThingDefinition
class ThingA extends GenericThing {
  test() {
    f1();
  }
}
```
 is just:
```
var result = (function () {const METHOD_NAME = "test";
function f1() {
    f2();
}


    f1();
}).apply(me, [])
```

In the transformer f2 is correcly collected as a dependency of the service but is not included in the transpiled service since f2 is not transpiled yet. I didn't understood the Transformer code good enough, but it seems like when visiting the nodes it compiles only the first level of dependencies discovered, maybe to avoid incidental infinite recursion.

A full ready to use example that reproduces the issue is on this fork: github.com/kklorenzotesta/ThingworxVSCodeProjectFunctionsOrderBug

**Comment by BogdanMihaiciuc** [comment]
Thanks I will look into this

**Comment by BogdanMihaiciuc** [comment]
You should be able to fix this by updating your `bm-thing-cli`/`bm-thing-transformer` dependencies to version 2.0.1.

Please reopen if you're still seeing this issue after updating.

**Comment by kklorenzotesta** [comment]
Thank you very much for the quick fix! I'll try it on monday
