### ISSUE TITLE
Validator with parameters support in Mashups

### ISSUE THREAD

**Issue by kklorenzotesta** [ptc-iot-sharing/ThingworxVSCodeProject#74]
I was wondering if is it possible to define a Validator with input parameters in the tsx mashups. Or only validators without parameters are possible at the moment?

**Comment by BogdanMihaiciuc** [comment]
You can, but there is no typing support for the parameters and there is no fancy way to declare them like with mashup parameters. What you have to do is to create a JSON file that contains the definition of your parameters, which looks like this:
```json
[
    {
        "BaseType": "STRING",
        "DefaultValue": "",
        "Description": "",
        "ParameterName": "test",
        "bindingDirection": "Target",
        "bindingType": "Property",
        "isBindingSource": false,
        "isBindingTarget": true,
        "shown": true
    },
    {
        "BaseType": "NUMBER",
        "Description": "",
        "ParameterName": "test2",
        "bindingDirection": "Target",
        "bindingType": "Property",
        "isBindingSource": false,
        "isBindingTarget": true,
        "shown": true
    }
]
```

Then, when you create the validator, you have to use a `Dynamic` namespace to specify the properties that it creates based on its configuration. Namely these are the hidden parameter defs property and the bindings for your parameters:
```tsx
<Validator
    Dynamic:_currentParameterDefs={importJSON("./ValidatorParameters.json")}
    Dynamic:test={QueryImplementingThings.SelectedRows.name}
    Dynamic:test2={10}
    Expression="test.length == test2"
    AutoEvaluate
    True={[QueryImplementingThings]}
/>
```

`Expression` and likely the new `Validator2` and `Expression2` also work the same way.

**Comment by kklorenzotesta** [comment]
That's great! thank you very much for the help!
