### ISSUE TITLE
User/Session bindings support in Mashups

### ISSUE THREAD

**Issue by kklorenzotesta** [ptc-iot-sharing/ThingworxVSCodeProject#76]
Is it currently possible to define bindings with the fields of User or Session in the tsx mashups?
(the session properties in the screenshot are from a custom UserSessionShape)
![image](https://github.com/ptc-iot-sharing/ThingworxVSCodeProject/assets/26228693/23935a56-f776-496c-a476-5126170e292b)
![image](https://github.com/ptc-iot-sharing/ThingworxVSCodeProject/assets/26228693/00368b41-02ee-44c8-a4a0-b19ef32256be)

**Comment by BogdanMihaiciuc** [comment]
There is currently no support for this, in a way that would translate to bindings to those sections in the mashup panel. What you can do instead is to pull those properties via a service (e.g. GetPropertyValues on a user entity or GetGlobalSessionValues on the current session info resource)

**Comment by kklorenzotesta** [comment]
ok, thank you for the help!
