### ISSUE TITLE
Bindings with mashup parameters don't work correctly

### ISSUE THREAD

**Issue by kklorenzotesta** [ptc-iot-sharing/ThingworxVSCodeProject#77]
In some situation declaring bindings in .tsx files using mashup parameters don't work.
In particular when passing a mashup parameter to the Navigation widget to use as a parameter for the target mashup than undefined is passed to the target mashup. Using Navigationfunction the parameter is not passed at all.
I created an example of the bugged behavior in the repository [kklorenzotesta/ThingworxVSCodeProjectMashupParameters](https://github.com/kklorenzotesta/ThingworxVSCodeProjectMashupParameters).
This repository contains two mashups:
```
import "bm-thing-transformer/ui";
import "../ui-static/widgets";

const goToMashup2 = defineWidget<"Mashup2">(Navigation);
const goToMashup2Function = defineWidget<"Mashup2">(Navigationfunction);
const MashupParameters = defineMashup(
  class {
    myInput!: STRING;
  }
);

export class Mashup1 extends MashupBase {
  renderMashup() {
    return (
      <Mashup ref={MashupParameters}>
        <Button
          Clicked={[goToMashup2.Navigate]}
          Label="Navigation"
        />
        <Button
          Clicked={[goToMashup2Function.Navigate]}
          Label="Navigationfunction"
        />
        <Label Text={MashupParameters.myInput} />
        <Navigation
          MashupName="Mashup2"
          TargetWindow="replace"
          ref={goToMashup2}
          Visible={false}
          myInput={MashupParameters.myInput}
        />
        <Navigationfunction
          TargetMashup="Mashup2"
          TargetWindowType="replace"
          ref={goToMashup2Function}
          myInput={MashupParameters.myInput}
        />
      </Mashup>
    );
  }
}
```
This Mashup1 has two buttons to navigate to Mashup2 using respectively Navigation and Navigationfunction widgets. In the first case the input of Mashup2 is undefined while in the second is missing entirely.
Using Navigation I can correctly set the Mashup2 parameter if it come from a Service.
The binding from the parameter to the Text of the Label also doesn't work.

Mashup2 is defined as follows:

```
import "bm-thing-transformer/ui";
import "../ui-static/widgets";

const MashupParameters = defineMashup(
  class {
    myInput!: STRING;
  }
);

export class Mashup2 extends MashupBase {
  renderMashup() {
    return (
      <Mashup ref={MashupParameters}>
        <Label Text={MashupParameters.myInput} />
      </Mashup>
    );
  }
}
```

**Comment by BogdanMihaiciuc** [comment]
I will take a look and try to fix this week. Thanks for reporting

**Comment by BogdanMihaiciuc** [comment]
I updated transformer/cli to version 2.1.6 which should resolve these problems and generate entities with correctly configured bindings.

Please reopen this if you're still encountering issues with mashup or navigation parameter bindings.
