### ISSUE TITLE
Support for using AppKeys

### ISSUE THREAD

**Issue by carlo-quinonez** [ptc-iot-sharing/ThingworxVSCodeProject#9]
We're trying to support using an `appKey` to deploy to ThingWorx instead of a username/password. Are you open to a PR for this?

**Comment by BogdanMihaiciuc** [comment]
Yes, of course.

**Comment by BogdanMihaiciuc** [comment]
Merged with a few changes: https://github.com/ptc-iot-sharing/ThingworxVSCodeProject/pull/11
